package com.backend.StockLinker.Audit_Service.Enums;

public enum AuditAction {

    // AUTH & TOKENS
    LOGIN, LOGIN_FAILED, GUEST_LOGIN, ROLE_SELECTED, ROLE_SELECTION_FAILED,
    REFRESH_TOKEN_CREATED, TOKEN_ROTATED, TOKEN_REVOKED, REPLAY_ATTACK,
    LOGOUT, LOGOUT_ALL, DEVICE_UPDATED, DEVICE_REGISTERED, NEW_DEVICE_LOGIN,
    DEVICE_REMOVED, DEVICE_MISMATCH, INVALID_TOKEN, EXPIRED_TOKEN, ACCESS_TOKEN_CREATED,

    ONBOARDING_STARTED,
    BUSINESS_UPDATED,
    ONBOARDING_COMPLETED,

    PROFILE_UPDATED,
    STORE_UPDATED,
    DELIVERY_INSIGHTS_UPDATED,
    STOREFRONT_VIEWED,
    RATING_SUBMITTED,

    CONNECTION_REQUESTED,
    CONNECTION_ACCEPTED,
    ARRIVAL_ANNOUNCED,

    ORDER_PLACED,
    ORDER_ACCEPTED,
    ORDER_REJECTED,
    DELIVERY_SEQUENCE_UPDATED,
    ROUTE_STARTED,
    ORDER_DELIVERED,

    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    INVENTORY_EXPORTED,

    CONVERSATION_STARTED,
    MESSAGE_SENT,
    MESSAGE_EDITED,
    MESSAGE_DELETED,
    MESSAGE_READ,

    ENQUIRY_ACCEPTED,
    NOTIFICATION_READ,
    NOTIFICATIONS_CLEARED,

    BULK_PRODUCTS_ADDED,
    ENQUIRY_SUBMITTED,




}