package com.backend.StockLinker.AuthService.constant;

public enum AuditAction {

    // AUTHENTICATION
    LOGIN, 
    LOGIN_FAILED, 
    LOGOUT, 
    LOGOUT_ALL,
    TOKEN_REFRESH, 
    TOKEN_REFRESH_FAILED,
    REGISTER, 
    PASSWORD_CHANGE,
    PASSWORD_RESET_REQUEST,
    PASSWORD_RESET_COMPLETE,
    
    // ROLE & PERMISSION
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    PERMISSION_CREATED,
    PERMISSION_UPDATED,
    PERMISSION_DELETED,
    
    // USER MANAGEMENT
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_ACCOUNT_LOCKED,
    USER_ACCOUNT_UNLOCKED,
    
    // DEVICE
    DEVICE_REGISTERED,
    DEVICE_REMOVED,
    DEVICE_TRUSTED,
    DEVICE_UNTRUSTED,
    
    // BUSINESS
    BUSINESS_CREATED,
    BUSINESS_UPDATED,
    BUSINESS_DELETED,
    
    // PRODUCT
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_VIEWED,
    
    // ORDER
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_CANCELLED,
    ORDER_VIEWED,
    
    // REVIEW
    REVIEW_CREATED,
    REVIEW_UPDATED,
    REVIEW_DELETED,
    
    // SYSTEM
    SYSTEM_CONFIG_CHANGED,
    DATA_EXPORTED,
    DATA_IMPORTED
}