package com.backend.StockLinker.AuthService.enums;

public enum AuditAction {

    // OAUTH & OTP
    GOOGLE_LOGIN_SUCCESS,
    GOOGLE_LOGIN_FAILED,
    OTP_LOGIN_SUCCESS,
    OTP_LOGIN_FAILED,
    GUEST_LOGIN,

    // ONBOARDING
    ONBOARDING_STARTED,
    ONBOARDING_COMPLETED,

    // SESSION & TOKENS
    TOKEN_REFRESH,
    TOKEN_REFRESH_FAILED,
    EXPIRED_TOKEN,
    INVALID_TOKEN,
    DEVICE_MISMATCH,
    TOKEN_REVOKED,
    TOKEN_ROTATED,
    REFRESH_TOKEN_CREATED,
    ACCESS_TOKEN_CREATED,
    REPLAY_ATTACK,
    LOGOUT,
    LOGOUT_ALL,

    // AUTHENTICATION
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAILED,

    // ACCOUNT & PROFILE
    ACCOUNT_BLOCKED,
    ACCOUNT_UNBLOCKED,
    PROFILE_UPDATED,
    PERMISSION_DENIED,

    // ROLE & PERMISSION
    ROLE_SELECTED,
    ROLE_SELECTION_FAILED,
    ROLE_CHANGED,
    PERMISSION_CHANGED,
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,

    // USER MANAGEMENT
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_ACCOUNT_LOCKED,
    USER_ACCOUNT_UNLOCKED,

    // DEVICE
    DEVICE_REGISTERED,
    DEVICE_UPDATED,
    NEW_DEVICE_LOGIN,
    DEVICE_REMOVED,
    DEVICE_TRUSTED,
    DEVICE_UNTRUSTED,

    // BUSINESS
    BUSINESS_CREATED,
    BUSINESS_UPDATED,
    BUSINESS_DELETED,

    // PRODUCT
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_VIEWED,

    // ORDER
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_CANCELLED,
    ORDER_VIEWED
}