package com.backend.StockLinker.AuthService.enums;

public enum AuditAction {


    GOOGLE_LOGIN_SUCCESS,

    GOOGLE_LOGIN_FAILED,

    OTP_LOGIN_SUCCESS,

    OTP_LOGIN_FAILED,

    GUEST_LOGIN,

    ROLE_SELECTED,

    ROLE_SELECTION_FAILED,

    ONBOARDING_STARTED,

    ONBOARDING_COMPLETED,

    TOKEN_REFRESH,

    TOKEN_REFRESH_FAILED,

    LOGOUT,

    LOGOUT_ALL,

    DEVICE_REGISTERED,

    DEVICE_UPDATED,

    NEW_DEVICE_LOGIN,

    ACCOUNT_BLOCKED,

    ACCOUNT_UNBLOCKED,

    PERMISSION_CHANGED,

    ROLE_CHANGED,

    // AUTHENTICATION
    LOGIN, 
    LOGIN_SUCCESS,
    LOGIN_FAILED,


    PROFILE_UPDATED,
    PERMISSION_DENIED,


    // ROLE & PERMISSION
    ROLE_ASSIGNED,
    ROLE_REMOVED,
    PERMISSION_GRANTED,
    PERMISSION_REVOKED,
    
    // USER MANAGEMENT
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    USER_BLOCKED,
    USER_UNBLOCKED,
    USER_ACCOUNT_LOCKED,
    USER_ACCOUNT_UNLOCKED,
    
    // DEVICE
    DEVICE_REMOVED,
    DEVICE_TRUSTED,
    DEVICE_UNTRUSTED,
    
    // BUSINESS
    BUSINESS_CREATED,
    BUSINESS_UPDATED,
    BUSINESS_DELETED,
    
    // PRODUCT
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    PRODUCT_VIEWED,
    
    // ORDER
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_CANCELLED,
    ORDER_VIEWED,   
}